// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnraUyXSFGy_O-Mb31qtZsxNGY0TtAPbI',
    appId: '1:339029969265:web:010c8942acd53d6eb34ed0',
    messagingSenderId: '339029969265',
    projectId: 'square-pants',
    authDomain: 'square-pants.firebaseapp.com',
    databaseURL: 'https://square-pants-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'square-pants.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3uEgaIiwBKv_evPQSg67zUvuiFjI9d0',
    appId: '1:339029969265:android:cf576d3262198dcfb34ed0',
    messagingSenderId: '339029969265',
    projectId: 'square-pants',
    databaseURL: 'https://square-pants-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'square-pants.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp19wWqxYN_05eZzlBB1_T3dNufWdbnao',
    appId: '1:339029969265:ios:abd28376f5daf4cab34ed0',
    messagingSenderId: '339029969265',
    projectId: 'square-pants',
    databaseURL: 'https://square-pants-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'square-pants.appspot.com',
    iosBundleId: 'com.example.squarePants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp19wWqxYN_05eZzlBB1_T3dNufWdbnao',
    appId: '1:339029969265:ios:abd28376f5daf4cab34ed0',
    messagingSenderId: '339029969265',
    projectId: 'square-pants',
    databaseURL: 'https://square-pants-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'square-pants.appspot.com',
    iosBundleId: 'com.example.squarePants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnraUyXSFGy_O-Mb31qtZsxNGY0TtAPbI',
    appId: '1:339029969265:web:c8a5961e78404f28b34ed0',
    messagingSenderId: '339029969265',
    projectId: 'square-pants',
    authDomain: 'square-pants.firebaseapp.com',
    databaseURL: 'https://square-pants-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'square-pants.appspot.com',
  );
}
